version: '3'
services:
  mariadb:
    image: kazaoki/mariadb-mroonga:latest
    # image: mariadb:latest
    container_name: mariadb
    restart: always
    command: ['--ft-min-word-len=2', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    ports:
      - ${MONGO_PORT}:27017
  redis-cache:
    image: redis:latest
    container_name: chosung_bible_cache
    restart: always
    volumes:
      - ${REDIS_CONF_PATH}/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_CACHE_PORT}:6379
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
  redis-mq:
    image: redis:latest
    container_name: chosung_bible_mq
    restart: always
    ports:
      - ${REDIS_MQ_PORT}:6379
