version: "3"
services:
  mariadb:
    image: kazaoki/mariadb-mroonga:latest
    # image: mariadb:latest
    container_name: mariadb
    restart: always
    command: ["--ft-min-word-len=2"]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    ports:
      - ${MONGO_PORT}:27017
